name: Build and Deploy Hugo site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Sjekk ut repoet
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Installer Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # 3. Rygg opp i cache og gamle filer
      - name: Clean Hugo resources
        run: rm -rf resources/ public/

      - name: Hugo diag build (verbose)
        run: |
          echo "Hugo version:"
          hugo version
          echo
          echo "Hugo env:"
          hugo env
          echo
          echo "Config files Hugo faktisk bruker:"
          hugo config | sed -n '1,120p'
          echo
          echo "==== Run with diagnostics (no deploy) ===="
          # Først: strengt prod-build
          hugo --minify --environment production --baseURL "https://kolbergvolley.no/" \
               --printI18nWarnings --printPathWarnings --printUnusedTemplates --debug
          echo
          echo "==== Telle filer i output ===="
          OUTDIR="public"; [ -d www ] && OUTDIR="www"
          echo "OUTDIR=$OUTDIR"
          find "$OUTDIR" -maxdepth 2 -type f | sed -n '1,120p'
          echo
          echo "==== Grep etter localhost i output ===="
          (grep -RIn "localhost" "$OUTDIR" || true) | sed -n '1,120p'

      # 4. Bygg nettstedet
      - name: Build site
        run: |
          hugo --minify \
               --environment production \
               --baseURL "https://kolbergvolley.no/"

      # 5. Deploy til server (samme som du brukte før)
      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.DEPLOY_SERVER }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          TARGET: ${{ secrets.DEPLOY_PATH }}
          EXCLUDE: "/.git/, /node_modules/"
